---
author: 
  name: "Seafood Globalization Lab"
  affiliation: "School of Aquatic and Fishery Sciences, University of Washington"
  orcid: "0000-0000-0000-0000"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: simplex
    toc: yes
editor_options: 
  chunk_output_type: console
params: 
  countries_i: NULL
  artis_eez_i: NULL
  artis_sau_i: NULL

---

```{r setup, include=FALSE}

# set global code chunk options
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE,
                      warning = FALSE)

# load packages
library(rmarkdown)
library(knitr) # Need package version 1.44 or up for quarto
library(countrycode) # convert and standardize country id
library(magrittr) # pipe function
library(ggplot2) # visualization
library(exploreARTIS) # custom ARTIS viz package 
library(forcats) #reorder factors

# iso3c to country name
country_name <- countrycode(params$countries_i,
                            origin = "iso3c",
                            destination = "country.name")

```

---
title: "Oceana Distant Water Fishing Report: `r country_name`"
---

# Introduction

This report provides an analysis of `r country_name`'s distant water fishing.

# Data Analysis

```{r last-5-years}
# calculate last 5 years in country specific data
max_year <- max(params$artis_eez_i$year)
last_5_yrs <- seq(max_year - 4, max_year, by = 1)

# df with focal countries most recent 5 years of data
artis_eez_i_5yr <- artis_eez_i %>% 
  filter(year %in% last_5_yrs)
```

```{r graph-colors}
# copy and paste exploreARTIS:: colors
region6_palette <- c(
  "#741A32", # maroon
  "#B34232", # burnt orange
  "#D38F35", #  orange
  "#D4B95F", # khaki
  "#4FA2A2", # teal
  "#114F59" # dark teal
)
artis_palette <- grDevices::colorRampPalette(region6_palette)
```

## DWF Activities

### Percent of catch in foreign waters over time

```{r prct-dwf}
# calc total catch
catch_total_yr <- artis_eez_i_5yr %>% 
  group_by(year) %>% 
  summarise(total_catch = sum(live_weight_t))

# calc total dwf catch & join to total catch
catch_dwf_yr <- artis_eez_i_5yr %>% 
  filter(dwf == "foreign") %>% 
  group_by(year) %>% 
  summarize(dwf_catch = sum(live_weight_t)) %>% 
  left_join(catch_total_yr, by = "year") %>% 
  mutate(prct_dwf = dwf_catch/total_catch)

# Line time series percent of total catch in foreign waters
(fig_dwf_prct <- catch_dwf_yr %>% 
  ggplot(aes(year,prct_dwf)) +
    geom_line() +
    theme_bw() +
    labs(y = "Percent Catch in Foreign Waters",
         x = "") +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1), 
                       limits = c(0,1))
)
```

### DWF catch by EEZ

```{r, eval=FALSE}
# DWF catch x EEZ x year
catch_eez_yr <- artis_eez_i_5yr %>% 
  filter(dwf == "foreign") %>% 
  group_by(year, catch_artis_country_name) %>% 
  summarise(catch = sum(live_weight_t)) %>%
  # remove grouping structure for complete
  ungroup() %>%
  # make implicit zeros explicit
  complete(year, catch_artis_country_name, fill = list(catch = 0)) %>% 
  # make column names match standard artis column names for exploreARTIS 
  rename(live_weight_t = catch,
         year = year,
         producer_iso3c = catch_artis_country_name
         )
# plot
exploreARTIS::plot_ts(test,
                      artis_var = "producer_iso3c",
                      plot.title = "DWF Catch by EEZ",
                      prop_flow_cutoff = 0.05,
                      plot.type = "stacked",
                      legend.title = "EEZ"
                      )
```


```{r, echo=FALSE}

# print top 25 DWF species
top_25 <- params$artis_eez_i %>% 
  filter(dwf == "foreign") %>%
  group_by(sciname) %>%
  summarise(live_weight_t = sum(live_weight_t)) %>%
  arrange(desc(live_weight_t)) %>%
  slice_head(n = 25) # limits df to first 25 rows

knitr::kable(
  top_25, caption = 'Top 25 DWF Species'
)
```




#### `r top_25[[1,1]]`

loop through this graph generation?

```{r, echo=FALSE, fig.cap="Source Country Without Catch EEZ Information"}

# plot artis_sau$source_country_iso3c (without catch eez information)
params$artis_eez_i %>%
 # select(-source_country_iso3c) %>%
 # rename("source_country_iso3c" = "catch_artis_iso3") %>%
  filter(sciname == top_25[[1,1]]) %>%
  plot_sankey()
```

```{r, echo=FALSE, fig.cap="EEZ of Catch for Source Country"}

# plot with catch eez information
params$artis_eez_i %>%
  select(-source_country_iso3c) %>%
  rename("source_country_iso3c" = "catch_artis_iso3") %>%
  filter(sciname == top_25[[1,1]]) %>%
  plot_sankey()
```

#### `r top_25[[2,1]]`

```{r, echo=FALSE, fig.cap="Source Country Without Catch EEZ Information"}

# plot artis_sau$source_country_iso3c (without catch eez information)
params$artis_eez_i %>%
 # select(-source_country_iso3c) %>%
 # rename("source_country_iso3c" = "catch_artis_iso3") %>%
  filter(sciname == top_25[[2,1]]) %>%
  plot_sankey()
```

```{r, echo=FALSE, fig.cap="EEZ of Catch for Source Country"}

# plot with catch eez information
params$artis_eez_i %>%
  select(-source_country_iso3c) %>%
  rename("source_country_iso3c" = "catch_artis_iso3") %>%
  filter(sciname == top_25[[2,1]]) %>%
  plot_sankey()
```
